### ISSUE TITLE
Skysim should be in a radius, not a rectangle, around the sky

### ISSUE THREAD

**Issue by pwc** [leoniechevalier/ECR-Workshop#2]
Currently we generate positions in a 1°×1° box around Andromeda

![image](https://github.com/leoniechevalier/ECR-Workshop/assets/192753/6f22ef06-8045-4c48-bbbe-3abbdd99b215)

We should really be within a certain radius

Subtasks:
- [x] Create a new feature branch to resolve this
- [x] Implement `crop_to_circle` function
- [x] Add `radius` parameter to the function
- [x] Fix function to use `radius` parameter
- [x] Update documentation

**Comment by leoniechevalier** [comment]
i fixed things
